# import variables from calling scripts
Import(['env_copy', 'USE_OSG'])

# add moby libraries to libraries used by env_copyironment
env_copy['LIBS'].append('moby')

# build utilities that do require Moby
env_copy.Program('adjust-center.cpp')
env_copy.Program('convexify.cpp')
env_copy.Program('conv-decomp.cpp')
env_copy.Program('center.cpp')

# build the symbolic output program
env_copy.Program('output-symbolic.cpp')

# build the driver program
env_copy.Program('driver.cpp')

# build symbolic chain
SConscript(['chain_contact/SConscript'], exports='env_copy')

# build controllers
SConscript(['mrobot/SConscript'], exports='env_copy')
SConscript(['contact_simple/SConscript'], exports='env_copy')
SConscript(['banditII/SConscript'], exports='env_copy')

