Moby: Moby::CompGeom Class Reference
Moby::CompGeom Class Reference
Class for performing assorted computational geometry functions.
#include <CompGeom.h>
Public Types
enum SegSegIntersectType { eSegSegNoIntersect, eSegSegIntersect, eSegSegVertex, eSegSegEdge }
enum LineLineIntersectType { eLineLineNoIntersect, eLineLineIntersect, eLineLineVertex, eLineLineEdge }
enum SegTriIntersectType {
eSegTriNoIntersect, eSegTriInclFace, eSegTriInclVertex, eSegTriInclEdge,
eSegTriInside, eSegTriVertex, eSegTriEdge, eSegTriFace,
eSegTriEdgeOverlap, eSegTriPlanarIntersect
}
enum SegPlaneIntersectType {
eSegPlaneInPlane, eSegPlaneToSide, eSegPlaneFirst, eSegPlaneSecond,
eSegPlaneOtherIntersect
}
enum PolygonLocationType { ePolygonInside, ePolygonOutside, ePolygonOnVertex, ePolygonOnEdge }
enum SegLocationType { eSegInterior, eSegOrigin, eSegEndpoint, eSegOutside }
enum OrientationType { eLeft, eOn, eRight }
enum VisibilityType { eVisible, eInvisible, eCoplanar }
Public Member Functions
template<class BidirectionalIterator >
bool diagonalie (BidirectionalIterator a, BidirectionalIterator b, BidirectionalIterator begin, BidirectionalIterator end, double tol)
Utility method for triangulate_polygon_2D()
template<class BidirectionalIterator >
bool diagonal (BidirectionalIterator a, BidirectionalIterator b, BidirectionalIterator begin, BidirectionalIterator end, double tol)
Utility method for triangulate_polygon_2D()
template<class BidirectionalIterator >
bool in_cone (BidirectionalIterator a, BidirectionalIterator b, BidirectionalIterator begin, BidirectionalIterator end, double tol)
Utility method for triangulate_polygon_2D()
template<class BidirectionalIterator , class OutputIterator >
OutputIterator triangulate_polygon_2D (BidirectionalIterator begin, BidirectionalIterator end, OutputIterator outbegin, double tol)
Triangulates a polygon (in 2D)
template<class ForwardIterator >
Point3d calc_centroid_3D (ForwardIterator first, ForwardIterator last)
Computes the centroid of a set of facets.
template<class ForwardIterator >
void determine_seg_endpoints (ForwardIterator begin, ForwardIterator end, std::pair< Point3d *, Point3d * > &endpoints)
Determines the endpoints for a container of collinear Ravelin::Vector3d objects.
template<class ForwardIterator >
void determine_seg_endpoints (ForwardIterator begin, ForwardIterator end, std::pair< Point3d, Point3d > &endpoints)
Determines the endpoints for a container of collinear Ravelin::Vector3d objects.
template<class ForwardIterator >
void determine_seg_endpoints (ForwardIterator begin, ForwardIterator end, std::pair< Point2d, Point2d > &endpoints)
Determines the endpoints for a container of collinear Point2d objects.
template<class ForwardIterator >
void determine_seg_endpoints (ForwardIterator begin, ForwardIterator end, std::pair< Point2d *, Point2d * > &endpoints)
Determines the endpoints for a container of collinear Point2d* objects.
template<class ForwardIterator , class OutputIterator >
OutputIterator intersect_seg_polygon (ForwardIterator begin, ForwardIterator end, const LineSeg2 &seg, OutputIterator outbegin)
Computes the intersection of a polygon and a line segment.
template<class ForwardIterator >
TessellatedPolyhedronPtr calc_convex_hull (ForwardIterator first, ForwardIterator last)
Computes the 3D convex hull of a set of points.
template<class ForwardIterator >
double find_hs_interior_point (ForwardIterator start, ForwardIterator end, Ravelin::Origin3d &point)
Finds an interior point of a set of halfspaces using linear programming.
template<class ForwardIterator >
TessellatedPolyhedronPtr calc_hs_intersection (ForwardIterator start, ForwardIterator end, const Ravelin::Origin3d &interior_point)
Computes the halfspace intersection, returning the result as a convex polyhedron.
template<class ForwardIterator >
bool intersect_seg_convex_polygon (ForwardIterator begin, ForwardIterator end, const LineSeg2 &seg, double &te, double &tl, double tol)
Computes the intersection of a convex polygon and a line segment.
template<class ForwardIterator , class OutputIterator >
OutputIterator to_2D (ForwardIterator begin_source, ForwardIterator end_source, const Ravelin::Matrix3d &R, OutputIterator begin_target)
template<class ForwardIterator , class OutputIterator >
OutputIterator to_3D (ForwardIterator begin_source, ForwardIterator end_source, OutputIterator begin_target, const Ravelin::Matrix3d &RT, double offset)
template<class ForwardIterator >
bool ccw (ForwardIterator begin, ForwardIterator end, double tol)
template<class ForwardIterator >
bool ccw (ForwardIterator begin, ForwardIterator end, const Ravelin::Vector3d &normal, double tol)
template<class OutputIterator >
OutputIterator intersect_coplanar_tris (const Triangle &t1, const Triangle &t2, const Ravelin::Vector3d &normal, OutputIterator begin)
Intersects two coplanar triangles.
template<class ForwardIterator , class OutputIterator >
OutputIterator intersect_convex_polygons (ForwardIterator pbegin, ForwardIterator pend, ForwardIterator qbegin, ForwardIterator qend, const Ravelin::Vector3d &normal, OutputIterator isect_begin)
Intersects two polygons in 3D.
template<class ForwardIterator , class OutputIterator >
OutputIterator intersect_convex_polygons (ForwardIterator pbegin, ForwardIterator pend, ForwardIterator qbegin, ForwardIterator qend, OutputIterator isect_begin)
Intersects two convex polygons in 2D.
template<class OutputIterator >
unsigned advance (unsigned a, unsigned *aa, unsigned n, bool inside, const Point2d &p, OutputIterator &current)
Utility function for intersect_coplanar_tris()
template<class OutputIterator >
OutputIterator intersect_tris (const Triangle &t1, const Triangle &t2, OutputIterator begin)
Intersects two triangles in 3D and returns the points of intersection.
template<class ForwardIterator , class OutputIterator >
OutputIterator calc_convex_hull (ForwardIterator source_begin, ForwardIterator source_end, OutputIterator target_begin)
Calculates the convex hull of a set of points in 2D using quickhull.
template<class ForwardIterator , class OutputIterator >
OutputIterator calc_convex_hull (ForwardIterator source_begin, ForwardIterator source_end, const Ravelin::Vector3d &normal, OutputIterator target_begin)
Calculates the convex hull of a set of points that lie on a 2D manifold using quickhull.
template<class ForwardIterator >
bool is_convex_polygon (ForwardIterator begin, ForwardIterator end, double tol)
Determines whether a polygon in 2D is convex.
template<class ForwardIterator >
bool is_convex_polygon (ForwardIterator begin, ForwardIterator end, const Ravelin::Vector3d &normal, double tol)
Determines whether a polygon (in 3D) is convex.
template<class ForwardIterator , class OutputIterator >
OutputIterator triangulate_convex_polygon (ForwardIterator source_begin, ForwardIterator source_end, OutputIterator target_begin)
Triangulates a convex polygon in O(n)
template<class ForwardIterator >
double fit_plane (ForwardIterator begin, ForwardIterator end, Ravelin::Vector3d &normal, double &offset)
Attempts to fit a plane to a set of points.
template<class ForwardIterator >
void project_plane (ForwardIterator begin, ForwardIterator end, const Ravelin::Vector3d &normal, double offset)
Projects a set of points onto a plane.
template<class ForwardIterator >
CompGeom::PolygonLocationType polygon_location (ForwardIterator begin, ForwardIterator end, const Point2d &point)
Determines whether a 2D point is inside a polygon.
template<class ForwardIterator >
double calc_polygon_area (ForwardIterator begin, ForwardIterator end)
Computes the area of a polygon in 2D.
template<class ForwardIterator >
double calc_polygon_area (ForwardIterator begin, ForwardIterator end, const Ravelin::Vector3d &normal)
Computes the area of a polygon in 3D.
template<class ForwardIterator >
Point2d calc_centroid_2D (ForwardIterator begin, ForwardIterator end)
Computes the centroid of points on a plane.
template<class ForwardIterator >
Point3d calc_centroid_2D (ForwardIterator begin, ForwardIterator end, const Ravelin::Vector3d &normal)
Computes the 3D (2D) centroid of points on a plane.
template<class ForwardIterator >
void calc_min_area_bounding_rect (ForwardIterator begin, ForwardIterator end, Point2d &x1, Point2d &x2, Point2d &x3, Point2d &x4)
Computes the minimum area bounding rectangle of a set of points.
template<class OutputIterator >
OutputIterator intersect_tris (const Point2d t1[3], const Point2d t2[3], OutputIterator output_begin)
template<class OutputIterator >
OutputIterator intersect_seg_tri (const LineSeg2 &seg, const Point2d tri[3], OutputIterator output_begin)
Intersects a line segment and a triangle in 2D.
template<class T , class U >
double determine_line_param (const T &p0, const U &dir, const T &v)
Gets the parameter of a point on a line, v = p0 + dir*t, -inf <= t <= inf.
template<class OutputIterator >
OutputIterator intersect_segs (const LineSeg2 &s1, const LineSeg2 &s2, OutputIterator output_begin)
Intersects two line segments in 2D.
Static Public Member Functions
static SegLocationType determine_seg_location (const LineSeg3 &seg, double t)
Determines the feature for a line segment given a parameter.
static SegLocationType determine_seg_location (const LineSeg2 &seg, double t)
Determines the feature for a line segment given a parameter.
static unsigned get_num_intersects (SegSegIntersectType t)
Gets the number of intersections for a seg/seg intersection code.
static unsigned get_num_intersects (SegTriIntersectType t)
Gets the number of intersections for a seg/tri intersection code.
static unsigned get_num_intersects (LineLineIntersectType t)
Gets the number of intersections for a line/line intersection code.
static double determine_3D_to_2D_offset (const Ravelin::Origin3d &o, const Ravelin::Matrix3d &R)
static double determine_3D_to_2D_offset (const Ravelin::Vector3d &o, const Ravelin::Matrix3d &R)
static Ravelin::Matrix3d calc_3D_to_2D_matrix (const Ravelin::Vector3d &normal)
Computes the projection matrix to convert from 3D to 2D.
static Point3d generate_point_on_plane (const Ravelin::Vector3d &normal, double d)
Generates a point on a plane.
static bool intersect_noncoplanar_tris (const Triangle &t1, const Triangle &t2, Point3d &p1, Point3d &p2)
Intersects two non-coplanar triangles in 3D and returns the line of intersection.
static SegTriIntersectType intersect_seg_tri (const LineSeg3 &seg, const Triangle &t, Point3d &isect, Point3d &isect2, double tol=NEAR_ZERO)
Determines the intersection between a line segment and triangle in 3D.
static SegTriIntersectType intersect_seg_tri (const LineSeg2 &seg, const Point2d tri[3], Point2d &isect, Point2d &isect2, double tol=NEAR_ZERO)
Determines the intersection between a line segment and triangle in 2D.
static SegSegIntersectType intersect_segs (const LineSeg3 &s1, const LineSeg3 &s2, Point3d &isect, Point3d &isect2)
Determines whether two line segments in 3D intersect.
static double intersect_seg_plane (const Ravelin::Vector3d &nrm, double d, const LineSeg3 &seg)
static SegPlaneIntersectType intersect_seg_plane (const Triangle &tri, const LineSeg3 &seg, Point3d &isect, unsigned int &big_dim, double tol=NEAR_ZERO)
Determines the intersection between a line segment and a plane in 3D.
static SegSegIntersectType intersect_segs (const LineSeg2 &s1, const LineSeg2 &s2, Point2d &isect, Point2d &isect2)
Determines whether two line segments in 2D intersect.
static LineLineIntersectType intersect_lines (const Point2d &o1, const Ravelin::Vector2d &dir1, double min1, double max1, const Point2d &o2, const Ravelin::Vector2d &dir2, double min2, double max2, double &s, double &t)
Determines whether two lines/rays/segments in 2D intersect.
static bool collinear (const Point3d &a, const Point3d &b, const Point3d &c, double tol=NEAR_ZERO)
Determines whether three points are collinear.
static PolygonLocationType in_tri (const Point2d t[3], const Point2d &p, double tol=NEAR_ZERO)
Determines the intersection of a point on a 2D triangle.
static bool collinear (const Point2d &a, const Point2d &b, const Point2d &c, double tol=NEAR_ZERO)
Determines whether three points are collinear.
static long double volume (const Point3d &a, const Point3d &b, const Point3d &c, const Point3d &d)
Gets the volume of a tetrahedron composed of vertices a, b, c, d.
static long double volume (const Ravelin::Origin3d &a, const Ravelin::Origin3d &b, const Ravelin::Origin3d &c, const Ravelin::Origin3d &d)
static VisibilityType volume_sign (const Point3d &a, const Point3d &b, const Point3d &c, const Point3d &d, double tol=NEAR_ZERO)
Gets the sign of the volume of a tetrahedron composed of vertices a, b, c, d.
static VisibilityType volume_sign (const Ravelin::Origin3d &a, const Ravelin::Origin3d &b, const Ravelin::Origin3d &c, const Ravelin::Origin3d &d, double tol=NEAR_ZERO)
static bool coplanar (const Triangle &t1, const Triangle &t2, double tol=NEAR_ZERO)
Determines whether two triangles are coplanar.
static Ravelin::Origin3d to_3D (const Ravelin::Origin2d &p, const Ravelin::Matrix3d &RT)
static Ravelin::Origin3d to_3D (const Ravelin::Origin2d &p, const Ravelin::Matrix3d &RT, double offset)
static Ravelin::Origin2d to_2D (const Point3d &p, const Ravelin::Matrix3d &R)
static bool point_in_tri (const Point3d &p, const Triangle &t, double tol=NEAR_ZERO)
Function for testing whether a point is in a triangle.
static bool coplanar (const Point3d &a, const Point3d &b, const Point3d &c, const Point3d &d, double tol=NEAR_ZERO)
Determines whether four points are coplanar.
static double calc_dist (const LineSeg3 &line_seg, const Point3d &point, double &t, Point3d &closest)
Calculates the Euclidean distance between a line segment and a point in 3D.
static double calc_closest_points (const LineSeg3 &s1, const LineSeg3 &s2, Point3d &p1, Point3d &p2)
Computes the shortest line segment between two line segments in 3D.
static bool query_intersect_tri_tri (const Triangle &t1, const Triangle &t2)
static PolygonLocationType in_tri (const Triangle &t, const Point3d &p, double tol=NEAR_ZERO)
Determines the location of a point on a triangle.
static double sgn (double a, double b, double tol=NEAR_ZERO)
Returns a if b > 0, -a if b < 0, and 0 if b = 0.
static bool rel_equal (double x, double y, double tol=NEAR_ZERO)
Determines whether two numbers are relatively/absolutely equal to within some tolerance.
template<class T , class U >
static double determine_line_param (const T &p, const U &dir, const T &v)
Gets the parameter of a point on a line, v = p0 + dir*t, -inf <= t <= inf.
template<class OutputIterator >
static OutputIterator intersect_seg_tri (const LineSeg2 &seg, const Point2d tri[3], OutputIterator output_begin)
Intersects a line segment and a triangle in 2D.
template<class OutputIterator >
static OutputIterator intersect_segs (const LineSeg2 &s1, const LineSeg2 &s2, OutputIterator output_begin)
Intersects two line segments in 2D.
template<class OutputIterator >
static OutputIterator intersect_tris (const Point2d t1[3], const Point2d t2[3], OutputIterator output_begin)
template<class ForwardIterator >
static void calc_min_area_bounding_rect (ForwardIterator begin, ForwardIterator end, Point2d &p1, Point2d &p2, Point2d &p3, Point2d &p4)
Computes the minimum area bounding rectangle of a set of points.
template<class ForwardIterator , class OutputIterator >
static OutputIterator intersect_convex_polygons (ForwardIterator pbegin, ForwardIterator pend, ForwardIterator qbegin, ForwardIterator qend, const Ravelin::Vector3d &normal, OutputIterator isect_begin)
Intersects two polygons in 3D.
template<class ForwardIterator , class OutputIterator >
static OutputIterator intersect_convex_polygons (ForwardIterator pbegin, ForwardIterator pend, ForwardIterator qbegin, ForwardIterator qend, OutputIterator isect_begin)
Intersects two convex polygons in 2D.
template<class ForwardIterator >
static bool ccw (ForwardIterator begin, ForwardIterator end, const Ravelin::Vector3d &normal, double tol=NEAR_ZERO)
template<class ForwardIterator >
static bool ccw (ForwardIterator begin, ForwardIterator end, double tol=NEAR_ZERO)
template<class ForwardIterator >
static bool is_convex_polygon (ForwardIterator begin, ForwardIterator end, double tol=NEAR_ZERO)
Determines whether a polygon in 2D is convex.
template<class ForwardIterator >
static bool is_convex_polygon (ForwardIterator begin, ForwardIterator end, const Ravelin::Vector3d &normal, double tol=NEAR_ZERO)
Determines whether a polygon (in 3D) is convex.
template<class ForwardIterator , class OutputIterator >
static OutputIterator calc_convex_hull (ForwardIterator source_begin, ForwardIterator source_end, const Ravelin::Vector3d &normal, OutputIterator target_begin)
Calculates the convex hull of a set of points that lie on a 2D manifold using quickhull.
template<class ForwardIterator , class OutputIterator >
static OutputIterator calc_convex_hull (ForwardIterator source_begin, ForwardIterator source_end, OutputIterator target_begin)
Calculates the convex hull of a set of points in 2D using quickhull.
template<class ForwardIterator >
static PolygonLocationType polygon_location (ForwardIterator begin, ForwardIterator end, const Point2d &point)
Determines whether a 2D point is inside a polygon.
template<class ForwardIterator >
static Point2d calc_centroid_2D (ForwardIterator begin, ForwardIterator end)
Computes the centroid of points on a plane.
template<class ForwardIterator >
static Point3d calc_centroid_2D (ForwardIterator begin, ForwardIterator end, const Ravelin::Vector3d &normal)
Computes the 3D (2D) centroid of points on a plane.
template<class ForwardIterator >
static double calc_polygon_area (ForwardIterator begin, ForwardIterator end, const Ravelin::Vector3d &normal)
Computes the area of a polygon in 3D.
template<class ForwardIterator >
static double calc_polygon_area (ForwardIterator begin, ForwardIterator end)
Computes the area of a polygon in 2D.
template<class ForwardIterator >
static void project_plane (ForwardIterator begin, ForwardIterator end, const Ravelin::Vector3d &normal, double offset)
Projects a set of points onto a plane.
template<class ForwardIterator >
static double fit_plane (ForwardIterator begin, ForwardIterator end, Ravelin::Vector3d &normal, double &offset)
Attempts to fit a plane to a set of points.
template<class ForwardIterator , class OutputIterator >
static OutputIterator triangulate_convex_polygon (ForwardIterator source_begin, ForwardIterator source_end, OutputIterator target_begin)
Triangulates a convex polygon in O(n)
template<class OutputIterator >
static OutputIterator intersect_tris (const Triangle &t1, const Triangle &t2, OutputIterator begin)
Intersects two triangles in 3D and returns the points of intersection.
template<class OutputIterator >
static OutputIterator intersect_coplanar_tris (const Triangle &t1, const Triangle &t2, const Ravelin::Vector3d &normal, OutputIterator begin)
Intersects two coplanar triangles.
template<class ForwardIterator , class OutputIterator >
static OutputIterator to_2D (ForwardIterator begin, ForwardIterator end, const Ravelin::Matrix3d &R, OutputIterator begin_target)
template<class ForwardIterator , class OutputIterator >
static OutputIterator to_3D (ForwardIterator begin, ForwardIterator end, OutputIterator begin_target, const Ravelin::Matrix3d &RT, double offset)
template<class ForwardIterator >
static void determine_seg_endpoints (ForwardIterator begin, ForwardIterator end, std::pair< Point3d, Point3d > &endpoints)
Determines the endpoints for a container of collinear Ravelin::Vector3d objects.
template<class ForwardIterator >
static void determine_seg_endpoints (ForwardIterator begin, ForwardIterator end, std::pair< Point3d *, Point3d * > &endpoints)
Determines the endpoints for a container of collinear Ravelin::Vector3d objects.
template<class ForwardIterator >
static void determine_seg_endpoints (ForwardIterator begin, ForwardIterator end, std::pair< Point2d, Point2d > &endpoints)
Determines the endpoints for a container of collinear Point2d objects.
template<class ForwardIterator >
static void determine_seg_endpoints (ForwardIterator begin, ForwardIterator end, std::pair< Point2d *, Point2d * > &endpoints)
Determines the endpoints for a container of collinear Point2d* objects.
template<class ForwardIterator >
static TessellatedPolyhedronPtr calc_convex_hull (ForwardIterator first, ForwardIterator last)
Computes the 3D convex hull of a set of points.
template<class ForwardIterator >
static Point3d calc_centroid_3D (ForwardIterator first, ForwardIterator last)
Computes the centroid of a set of facets.
template<class ForwardIterator >
static TessellatedPolyhedronPtr calc_hs_intersection (ForwardIterator start, ForwardIterator end, const Ravelin::Origin3d &interior_point)
Computes the halfspace intersection, returning the result as a convex polyhedron.
template<class ForwardIterator >
static double find_hs_interior_point (ForwardIterator start, ForwardIterator end, Ravelin::Origin3d &point)
Finds an interior point of a set of halfspaces using linear programming.
template<class ForwardIterator >
static unsigned calc_dimensionality (ForwardIterator first, ForwardIterator last, double tol=NEAR_ZERO)
template<class ForwardIterator >
static bool intersect_seg_convex_polygon (ForwardIterator begin, ForwardIterator end, const LineSeg2 &seg, double &te, double &tl, double tol=NEAR_ZERO)
Computes the intersection of a convex polygon and a line segment.
template<class ForwardIterator , class OutputIterator >
static OutputIterator intersect_seg_polygon (ForwardIterator begin, ForwardIterator end, const LineSeg2 &seg, OutputIterator outbegin)
Computes the intersection of a polygon and a line segment.
template<class BidirectionalIterator , class OutputIterator >
static OutputIterator triangulate_polygon_2D (BidirectionalIterator begin, BidirectionalIterator end, OutputIterator begintarget, double tol=NEAR_ZERO)
Triangulates a polygon (in 2D)
template<class T >
static T point_on_seg (T a, T b, double t)
Returns the point a*t + (1-t)*b on the line segment ab.
Friends
class Polyhedron
template<class T , class V >
class CompGeomSpecOne
template<class T , class U , class V >
class CompGeomSpecTwo
Detailed Description
Class for performing assorted computational geometry functions.
Member Function Documentation
template<class OutputIterator > unsigned Moby::CompGeom::advance (unsigned a, unsigned * aa, unsigned n, bool inside, const Point2d & p, OutputIterator & current)
Utility function for intersect_coplanar_tris()
Taken from O'Rourke, p. 259.
template<class ForwardIterator > Point2d Moby::CompGeom::calc_centroid_2D (ForwardIterator begin, ForwardIterator end) static
Computes the centroid of points on a plane.
Parameters
begin an iterator to a polygon in 2D
end an iterator to a polygon in 2D
template<class ForwardIterator > Point3d Moby::CompGeom::calc_centroid_2D (ForwardIterator begin, ForwardIterator end, const Ravelin::Vector3d & normal) static
Computes the 3D (2D) centroid of points on a plane.
Parameters
poly a counter-clockwise oriented polygon in 3D
normal a vector normal to the plane that contains the points
template<class ForwardIterator > Point2d Moby::CompGeom::calc_centroid_2D (ForwardIterator begin, ForwardIterator end)
Computes the centroid of points on a plane.
Parameters
begin an iterator to a polygon in 2D
end an iterator to a polygon in 2D
template<class ForwardIterator > Point3d Moby::CompGeom::calc_centroid_2D (ForwardIterator begin, ForwardIterator end, const Ravelin::Vector3d & normal)
Computes the 3D (2D) centroid of points on a plane.
Parameters
poly a counter-clockwise oriented polygon in 3D
normal a vector normal to the plane that contains the points
template<class ForwardIterator > Point3d Moby::CompGeom::calc_centroid_3D (ForwardIterator first, ForwardIterator last)
Computes the centroid of a set of facets.
The facets may represent a polygon, a polyhedron, or even an open polyhedron. However, the facets may not intersect.
template<class ForwardIterator > Point3d Moby::CompGeom::calc_centroid_3D (ForwardIterator first, ForwardIterator last) static
Computes the centroid of a set of facets.
The facets may represent a polygon, a polyhedron, or even an open polyhedron. However, the facets may not intersect.
double CompGeom::calc_closest_points (const LineSeg3 & s1, const LineSeg3 & s2, Point3d & p1, Point3d & p2) static
Computes the shortest line segment between two line segments in 3D.
Parameters
s1 the first segment
s2 the second segment
p1 the closest point on s1 to s2 (on return)
p2 the closest point on s2 to s1 (on return)
Returns
the distance between p1 and p2
Note
algorithm taken from http://geometricalgorithms.com
template<class ForwardIterator , class OutputIterator > OutputIterator Moby::CompGeom::calc_convex_hull (ForwardIterator source_begin, ForwardIterator source_end, const Ravelin::Vector3d & normal, OutputIterator target_begin) static
Calculates the convex hull of a set of points that lie on a 2D manifold using quickhull.
Parameters
source_begin an iterator to the beginning of a container of points
source_end an iterator pointing to the end of a container of points
normal the (optional) normal of the points; this will be computed if normal is zero vector
target_begin an iterator to the beginning of a container of points; on return, contains the convex hull (NOTE: size of this container must be as large as the source container)
Returns
the new end of the target container
Referenced by Moby::CylinderPrimitive::get_mesh(), Moby::SpherePrimitive::get_mesh(), Moby::ConePrimitive::get_mesh(), and Moby::TriangleMeshPrimitive::set_mesh().
template<class ForwardIterator , class OutputIterator > OutputIterator Moby::CompGeom::calc_convex_hull (ForwardIterator source_begin, ForwardIterator source_end, OutputIterator target_begin) static
Calculates the convex hull of a set of points in 2D using quickhull.
Parameters
source_begin an iterator to the beginning of a container of Point2d or Point2d*
source_end an iterator pointing to the end of a container of Point2d or Point2d*
target_begin an iterator to the beginning of a container of indices; on return, contains the convex hull (NOTE: size of this container must be as large as the source container)
Returns
the new end of the target container
template<class ForwardIterator > TessellatedPolyhedronPtr Moby::CompGeom::calc_convex_hull (ForwardIterator first, ForwardIterator last) static
Computes the 3D convex hull of a set of points.
Parameters
first a forward iterator for type Ravelin::Vector3
last a forward iterator for type Ravelin::Vector3
Returns
a pointer to the newly created polyhedron
template<class ForwardIterator > TessellatedPolyhedronPtr Moby::CompGeom::calc_convex_hull (ForwardIterator first, ForwardIterator last)
Computes the 3D convex hull of a set of points.
Parameters
first a forward iterator for type Ravelin::Vector3
last a forward iterator for type Ravelin::Vector3
Returns
a pointer to the newly created polyhedron
template<class ForwardIterator , class OutputIterator > OutputIterator Moby::CompGeom::calc_convex_hull (ForwardIterator source_begin, ForwardIterator source_end, OutputIterator target_begin)
Calculates the convex hull of a set of points in 2D using quickhull.
Parameters
source_begin an iterator to the beginning of a container of Point2d or Point2d*
source_end an iterator pointing to the end of a container of Point2d or Point2d*
target_begin an iterator to the beginning of a container of indices; on return, contains the convex hull (NOTE: size of this container must be as large as the source container)
Returns
the new end of the target container
template<class ForwardIterator , class OutputIterator > OutputIterator Moby::CompGeom::calc_convex_hull (ForwardIterator source_begin, ForwardIterator source_end, const Ravelin::Vector3d & normal, OutputIterator target_begin)
Calculates the convex hull of a set of points that lie on a 2D manifold using quickhull.
Parameters
source_begin an iterator to the beginning of a container of points
source_end an iterator pointing to the end of a container of points
normal the (optional) normal of the points; this will be computed if normal is zero vector
target_begin an iterator to the beginning of a container of points; on return, contains the convex hull (NOTE: size of this container must be as large as the source container)
Returns
the new end of the target container
double CompGeom::calc_dist (const LineSeg3 & line_seg, const Point3d & point, double & t, Point3d & closest) static
Calculates the Euclidean distance between a line segment and a point in 3D.
Parameters
line_seg the two endpoints of the line segment
point the query point
t gives the parametric form line_seg.first + (line_seg.second - line_seg.first) * t
closest point on the line segment to point
template<class ForwardIterator > TessellatedPolyhedronPtr Moby::CompGeom::calc_hs_intersection (ForwardIterator start, ForwardIterator end, const Ravelin::Origin3d & interior_point) static
Computes the halfspace intersection, returning the result as a convex polyhedron.
Parameters
start an iterator to the start of a collection of halfspaces, each of type std::pair<Ravelin::Vector3, double>, where the vector [nx ny nz] is the normal to the halfspace and the scalar is the offset 'd'; each halfspace will satisfy the equation nx*x + ny*y + nz*z <= d
end an iterator to the end of the collection
interior_point a point interior to all of the halfspaces
Returns
a pointer to the created polyhedron or a NULL pointer if unsuccessful
template<class ForwardIterator > TessellatedPolyhedronPtr Moby::CompGeom::calc_hs_intersection (ForwardIterator start, ForwardIterator end, const Ravelin::Origin3d & interior_point)
Computes the halfspace intersection, returning the result as a convex polyhedron.
Parameters
start an iterator to the start of a collection of halfspaces, each of type std::pair<Ravelin::Vector3, double>, where the vector [nx ny nz] is the normal to the halfspace and the scalar is the offset 'd'; each halfspace will satisfy the equation nx*x + ny*y + nz*z <= d
end an iterator to the end of the collection
interior_point a point interior to all of the halfspaces
Returns
a pointer to the created polyhedron or a NULL pointer if unsuccessful
template<class ForwardIterator > void Moby::CompGeom::calc_min_area_bounding_rect (ForwardIterator begin, ForwardIterator end, Point2d & x1, Point2d & x2, Point2d & x3, Point2d & x4) static
Computes the minimum area bounding rectangle of a set of points.
Uses 2D convex hull and rotating calipers method; runs in O(N lg N) time On return, x1, x2, x3, and x4 are the four vertices of the bounding rectangle (ordered as edges).
template<class ForwardIterator > void Moby::CompGeom::calc_min_area_bounding_rect (ForwardIterator begin, ForwardIterator end, Point2d & x1, Point2d & x2, Point2d & x3, Point2d & x4)
Computes the minimum area bounding rectangle of a set of points.
Uses 2D convex hull and rotating calipers method; runs in O(N lg N) time On return, x1, x2, x3, and x4 are the four vertices of the bounding rectangle (ordered as edges).
template<class ForwardIterator > double Moby::CompGeom::calc_polygon_area (ForwardIterator begin, ForwardIterator end, const Ravelin::Vector3d & normal) static
Computes the area of a polygon in 3D.
Parameters
poly a counter-clockwise oriented polygon in 3D
normal a vector normal to the plane that contains the points
template<class ForwardIterator > double Moby::CompGeom::calc_polygon_area (ForwardIterator begin, ForwardIterator end) static
Computes the area of a polygon in 2D.
Parameters
poly a counter-clockwise oriented polygon in 2D
template<class ForwardIterator > double Moby::CompGeom::calc_polygon_area (ForwardIterator begin, ForwardIterator end)
Computes the area of a polygon in 2D.
Parameters
poly a counter-clockwise oriented polygon in 2D
template<class ForwardIterator > double Moby::CompGeom::calc_polygon_area (ForwardIterator begin, ForwardIterator end, const Ravelin::Vector3d & normal)
Computes the area of a polygon in 3D.
Parameters
poly a counter-clockwise oriented polygon in 3D
normal a vector normal to the plane that contains the points
template<class ForwardIterator > bool Moby::CompGeom::ccw (ForwardIterator begin, ForwardIterator end, const Ravelin::Vector3d & normal, double tol = NEAR_ZERO) static
Determines whether a polygon in 2D is counter-clockwise
Note
Degenerate polygons (alternating representation) will fail!
template<class ForwardIterator > bool Moby::CompGeom::ccw (ForwardIterator begin, ForwardIterator end, double tol = NEAR_ZERO) static
Determines whether a polygon in 2D is counter-clockwise
Note
Degenerate polygons (alternating representation) will fail!
template<class ForwardIterator > bool Moby::CompGeom::ccw (ForwardIterator begin, ForwardIterator end, double tol)
Determines whether a polygon in 2D is counter-clockwise
Note
Degenerate polygons (alternating representation) will fail!
template<class ForwardIterator > bool Moby::CompGeom::ccw (ForwardIterator begin, ForwardIterator end, const Ravelin::Vector3d & normal, double tol)
Determines whether a polygon in 2D is counter-clockwise
Note
Degenerate polygons (alternating representation) will fail!
template<class ForwardIterator > void Moby::CompGeom::determine_seg_endpoints (ForwardIterator begin, ForwardIterator end, std::pair< Point3d, Point3d > & endpoints) static
Determines the endpoints for a container of collinear Ravelin::Vector3d objects.
Parameters
begin iterator to beginning of container of type Ravelin::Vector3
end iterator to end of container of type Ravelin::Vector3
endpoints the two farthest points on the segment on return
template<class ForwardIterator > void Moby::CompGeom::determine_seg_endpoints (ForwardIterator begin, ForwardIterator end, std::pair< Point3d *, Point3d * > & endpoints) static
Determines the endpoints for a container of collinear Ravelin::Vector3d objects.
Parameters
begin iterator to beginning of container of type Ravelin::Vector3
end iterator to end of container of type Ravelin::Vector3
endpoints the two farthest points on the segment on return
template<class ForwardIterator > void Moby::CompGeom::determine_seg_endpoints (ForwardIterator begin, ForwardIterator end, std::pair< Point2d, Point2d > & endpoints) static
Determines the endpoints for a container of collinear Point2d objects.
Parameters
begin iterator to beginning of container of type Point2d
end iterator to end of container of type Point2d
endpoints the two farthest points on the segment on return
template<class ForwardIterator > void Moby::CompGeom::determine_seg_endpoints (ForwardIterator begin, ForwardIterator end, std::pair< Point2d *, Point2d * > & endpoints) static
Determines the endpoints for a container of collinear Point2d* objects.
Parameters
begin iterator to beginning of container of type Point2d*
end iterator to end of container of type Point2d*
endpoints the two farthest points on the segment on return
template<class ForwardIterator > void Moby::CompGeom::determine_seg_endpoints (ForwardIterator begin, ForwardIterator end, std::pair< Point3d *, Point3d * > & endpoints)
Determines the endpoints for a container of collinear Ravelin::Vector3d objects.
Parameters
begin iterator to beginning of container of type Ravelin::Vector3
end iterator to end of container of type Ravelin::Vector3
endpoints the two farthest points on the segment on return
template<class ForwardIterator > void Moby::CompGeom::determine_seg_endpoints (ForwardIterator begin, ForwardIterator end, std::pair< Point3d, Point3d > & endpoints)
Determines the endpoints for a container of collinear Ravelin::Vector3d objects.
Parameters
begin iterator to beginning of container of type Ravelin::Vector3
end iterator to end of container of type Ravelin::Vector3
endpoints the two farthest points on the segment on return
template<class ForwardIterator > void Moby::CompGeom::determine_seg_endpoints (ForwardIterator begin, ForwardIterator end, std::pair< Point2d, Point2d > & endpoints)
Determines the endpoints for a container of collinear Point2d objects.
Parameters
begin iterator to beginning of container of type Point2d
end iterator to end of container of type Point2d
endpoints the two farthest points on the segment on return
template<class ForwardIterator > void Moby::CompGeom::determine_seg_endpoints (ForwardIterator begin, ForwardIterator end, std::pair< Point2d *, Point2d * > & endpoints)
Determines the endpoints for a container of collinear Point2d* objects.
Parameters
begin iterator to beginning of container of type Point2d*
end iterator to end of container of type Point2d*
endpoints the two farthest points on the segment on return
template<class ForwardIterator > double Moby::CompGeom::find_hs_interior_point (ForwardIterator start, ForwardIterator end, Ravelin::Origin3d & point) static
Finds an interior point of a set of halfspaces using linear programming.
The method used to find the interior point is of order O(n), where n is the number of halfspace constraints.
Parameters
start an iterator to the start of a collection of halfspaces, each of type std::pair<Ravelin::Vector3, double>, where the vector [nx ny nz] is the normal to the halfspace and the scalar is the offset 'd'; each halfspace will satisfy the equation nx*x + ny*y + nz*z <= d
end an iterator to the end of the collection
point contains the interior point on return if successful
Returns
the minimum distance from a halfspace of the interior point; if the point is negative, there is no interior point
template<class ForwardIterator > double Moby::CompGeom::find_hs_interior_point (ForwardIterator start, ForwardIterator end, Ravelin::Origin3d & point)
Finds an interior point of a set of halfspaces using linear programming.
The method used to find the interior point is of order O(n), where n is the number of halfspace constraints.
Parameters
start an iterator to the start of a collection of halfspaces, each of type std::pair<Ravelin::Vector3, double>, where the vector [nx ny nz] is the normal to the halfspace and the scalar is the offset 'd'; each halfspace will satisfy the equation nx*x + ny*y + nz*z <= d
end an iterator to the end of the collection
point contains the interior point on return if successful
Returns
the minimum distance from a halfspace of the interior point; if the point is negative, there is no interior point
template<class ForwardIterator > double Moby::CompGeom::fit_plane (ForwardIterator begin, ForwardIterator end, Ravelin::Vector3d & normal, double & offset) static
Attempts to fit a plane to a set of points.
The singular value decomposition is used to determine the plane that fits the points best in a least-squares sense.
Parameters
points the set of points (in 3D)
normal contains the "best" normal, on return
offset the offset such that, for any point on the plane x, <normal, x> = offset
Returns
the maximum deviation from the plane
template<class ForwardIterator > double Moby::CompGeom::fit_plane (ForwardIterator begin, ForwardIterator end, Ravelin::Vector3d & normal, double & offset)
Attempts to fit a plane to a set of points.
The singular value decomposition is used to determine the plane that fits the points best in a least-squares sense.
Parameters
points the set of points (in 3D)
normal contains the "best" normal, on return
offset the offset such that, for any point on the plane x, <normal, x> = offset
Returns
the maximum deviation from the plane
CompGeom::PolygonLocationType CompGeom::in_tri (const Point2d t[3], const Point2d & p, double tol = NEAR_ZERO) static
Determines the intersection of a point on a 2D triangle.
Adapted from O'Rourke, p. 236.
Parameters
t the 2D triangle
p a 2D point
tol the tolerance with which to test for zero
Returns
ePolygonOnVertex if p coincides with a vertex of t, ePolygonOnEdge if p is in the relative interior of an edge of t, ePolygonInside if p is in the relative interior of t, or ePolygonOutside otherwise
CompGeom::PolygonLocationType CompGeom::in_tri (const Triangle & t, const Point3d & p, double tol = NEAR_ZERO) static
Determines the location of a point on a triangle.
Precondition
it has been determined that p lies in t's plane
template<class ForwardIterator , class OutputIterator > OutputIterator Moby::CompGeom::intersect_convex_polygons (ForwardIterator pbegin, ForwardIterator pend, ForwardIterator qbegin, ForwardIterator qend, const Ravelin::Vector3d & normal, OutputIterator isect_begin) static
Intersects two polygons in 3D.
Parameters
pbegin an iterator pointing to the container holding a ccw polygon
pend the end of the container holding the first polygon
qbegin an iterator pointing to the container holding a ccw polygon
qend the end of the container holding the second polygon
normal the normal to the polygons
isect_begin on return, the polygon of intersection will be placed here with ccw orientation; this container must be big enough to hold the result (i.e., it must be at least of size min(p,q)
Returns
the iterator pointing to the end of the container of intersection
template<class ForwardIterator , class OutputIterator > OutputIterator Moby::CompGeom::intersect_convex_polygons (ForwardIterator pbegin, ForwardIterator pend, ForwardIterator qbegin, ForwardIterator qend, OutputIterator isect_begin) static
Intersects two convex polygons in 2D.
Parameters
pbegin a random access iterator pointing to the container holding a ccw polygon (of Point2d)
pend the end of the container holding the first polygon (of Point2d)
qbegin a random access iterator pointing to the container holding a ccw polygon (of Point2d)
qend the end of the container holding the second polygon (of Point2d)
isect_begin on return, the polygon of intersection will be placed here with ccw orientation; this container must be big enough to hold the result (i.e., it must be at least of size min(p,q)
Returns
the iterator pointing to the end of the container of intersection
template<class ForwardIterator , class OutputIterator > OutputIterator Moby::CompGeom::intersect_convex_polygons (ForwardIterator pbegin, ForwardIterator pend, ForwardIterator qbegin, ForwardIterator qend, const Ravelin::Vector3d & normal, OutputIterator isect_begin)
Intersects two polygons in 3D.
Parameters
pbegin an iterator pointing to the container holding a ccw polygon
pend the end of the container holding the first polygon
qbegin an iterator pointing to the container holding a ccw polygon
qend the end of the container holding the second polygon
normal the normal to the polygons
isect_begin on return, the polygon of intersection will be placed here with ccw orientation; this container must be big enough to hold the result (i.e., it must be at least of size min(p,q)
Returns
the iterator pointing to the end of the container of intersection
template<class ForwardIterator , class OutputIterator > OutputIterator Moby::CompGeom::intersect_convex_polygons (ForwardIterator pbegin, ForwardIterator pend, ForwardIterator qbegin, ForwardIterator qend, OutputIterator isect_begin)
Intersects two convex polygons in 2D.
Parameters
pbegin a random access iterator pointing to the container holding a ccw polygon (of Point2d)
pend the end of the container holding the first polygon (of Point2d)
qbegin a random access iterator pointing to the container holding a ccw polygon (of Point2d)
qend the end of the container holding the second polygon (of Point2d)
isect_begin on return, the polygon of intersection will be placed here with ccw orientation; this container must be big enough to hold the result (i.e., it must be at least of size min(p,q)
Returns
the iterator pointing to the end of the container of intersection
template<class OutputIterator > OutputIterator Moby::CompGeom::intersect_coplanar_tris (const Triangle & t1, const Triangle & t2, const Ravelin::Vector3d & normal, OutputIterator begin) static
Intersects two coplanar triangles.
Parameters
normal a normal to both triangles
begin an iterator to a container that can hold the points of intersection (i.e., a container of size 6 or greater); on return, the container will contain a ccw polygon (in 3D) [orientation with respect to the given normal]
Returns
the end of the container output
template<class OutputIterator > OutputIterator Moby::CompGeom::intersect_coplanar_tris (const Triangle & t1, const Triangle & t2, const Ravelin::Vector3d & normal, OutputIterator begin)
Intersects two coplanar triangles.
Parameters
normal a normal to both triangles
begin an iterator to a container that can hold the points of intersection (i.e., a container of size 6 or greater); on return, the container will contain a ccw polygon (in 3D) [orientation with respect to the given normal]
Returns
the end of the container output
References Moby::Triangle::a, and Moby::Triangle::get_vertex().
CompGeom::LineLineIntersectType CompGeom::intersect_lines (const Point2d & o1, const Ravelin::Vector2d & dir1, double min1, double max1, const Point2d & o2, const Ravelin::Vector2d & dir2, double min2, double max2, double & s, double & t) static
Determines whether two lines/rays/segments in 2D intersect.
Taken from O'Rourke, p. 224.
Parameters
o1 the origin of the first line segment/ray (or a point on the line)
dir1 the direction of the first line
min1 the minimum parameter of the first line segment/ray/line
max1 the maximum parameter of the first line segment/ray/line
o2 the origin of the first line segment/ray (or a point on the line)
dir2 the direction of the second line
min2 the minimum parameter of the second line segment/ray/line
max2 the maximum parameter of the second line segment/ray/line
s1 on return of eLineLineIntersect/eLineLineVertex/eLineLineEdge contains the parameter on the first line of the first point of intersection (o1 + dir1*s1)
s2 on return of eLineLineEdge contains the parameter on the first line of the second point of intersection (o1 + dir1*s2)
Returns
the intersection type (edge, vertex, true_intersect, no_intersect); an edge intersection indicates that the lines/rays/segments collinearly overlap; vertex intersection indicates that an endpoint of one ray/segment is on the other line/ray/segment, but edge intersection does not hold; true_intersect indicates that the lines/rays/segments intersect at a single point.
bool CompGeom::intersect_noncoplanar_tris (const Triangle & t1, const Triangle & t2, Point3d & p1, Point3d & p2) static
Intersects two non-coplanar triangles in 3D and returns the line of intersection.
Parameters
t1 the first triangle
t2 the second triangle
p1 an endpoint of the line of intersection (on return)
p2 an endpoint of the line of intersection (on return)
Returns
true if the triangles intersect, false if they don't intersect or are coplanar
References Moby::Triangle::a, Moby::Triangle::b, and Moby::Triangle::c.
template<class ForwardIterator > bool Moby::CompGeom::intersect_seg_convex_polygon (ForwardIterator begin, ForwardIterator end, const LineSeg2 & seg, double & te, double & tl, double tol = NEAR_ZERO) static
Computes the intersection of a convex polygon and a line segment.
Parameters
begin iterator pointing to start of collection of Point2d elements
end iterator pointing to end of collection of Point2d elements
seg the line segment
te the parameter of the line segment for the beginning of the intersection; (1-te)*seg.first + te*seg.second is point of intersection
tl the parameter of the line segment for the end of the intersection; (1-tl)*seg.first + tl*seg.second is point of intersection
tol the tolerance for parallel lines
Returns
true if the two intersect and false otherwise
Note
polygon must be given in counter-clockwise order
first vertex should not appear twice
taken from http://geometryalgorithms.com
template<class ForwardIterator > bool Moby::CompGeom::intersect_seg_convex_polygon (ForwardIterator begin, ForwardIterator end, const LineSeg2 & seg, double & te, double & tl, double tol)
Computes the intersection of a convex polygon and a line segment.
Parameters
begin iterator pointing to start of collection of Point2d elements
end iterator pointing to end of collection of Point2d elements
seg the line segment
te the parameter of the line segment for the beginning of the intersection; (1-te)*seg.first + te*seg.second is point of intersection
tl the parameter of the line segment for the end of the intersection; (1-tl)*seg.first + tl*seg.second is point of intersection
tol the tolerance for parallel lines
Returns
true if the two intersect and false otherwise
Note
polygon must be given in counter-clockwise order
first vertex should not appear twice
taken from http://geometryalgorithms.com
CompGeom::SegPlaneIntersectType CompGeom::intersect_seg_plane (const Triangle & tri, const LineSeg3 & seg, Point3d & isect, unsigned int & big_dim, double tol = NEAR_ZERO) static
Determines the intersection between a line segment and a plane in 3D.
Parameters
tri a 3D triangle that is fully contained in the plane to be intersected
seg a 3D line segment
isect the point of intersection (on return)
big_dim the dimension of the largest component (on return)
NEAR_ZERO the tolerance to test for zero
Returns
the intersection type: eSegPlaneInPlane (segment lies wholly within the plane), eSegPlaneFirst (first vertex of segment is on the plane, but not the second), eSegPlaneSecond (second vertex of segment is on the plane, but not the first), eSegPlaneToSide (the segment lies strictly to one side or the other of the plane), or eSegPlaneOtherIntersect (segment intersects the plane, and in-plane, first, and second do not hold).
template<class ForwardIterator , class OutputIterator > OutputIterator Moby::CompGeom::intersect_seg_polygon (ForwardIterator begin, ForwardIterator end, const LineSeg2 & seg, OutputIterator outbegin) static
Computes the intersection of a polygon and a line segment.
Parameters
begin iterator pointing to start of collection of Point2d elements
end iterator pointing to end of collection of Point2d elements
seg the line segment
outbegin an iterator to a container of type LineSeg2 that will store line segments on/in the polygon on return
tol the tolerance for parallel lines
Returns
ePolygonSegInside if the polygon
Note
polygon must be given in counter-clockwise order
first vertex should not appear twice
template<class ForwardIterator , class OutputIterator > OutputIterator Moby::CompGeom::intersect_seg_polygon (ForwardIterator begin, ForwardIterator end, const LineSeg2 & seg, OutputIterator outbegin)
Computes the intersection of a polygon and a line segment.
Parameters
begin iterator pointing to start of collection of Point2d elements
end iterator pointing to end of collection of Point2d elements
seg the line segment
outbegin an iterator to a container of type LineSeg2 that will store line segments on/in the polygon on return
tol the tolerance for parallel lines
Returns
ePolygonSegInside if the polygon
Note
polygon must be given in counter-clockwise order
first vertex should not appear twice
CompGeom::SegTriIntersectType CompGeom::intersect_seg_tri (const LineSeg3 & seg, const Triangle & t, Point3d & isect, Point3d & isect2, double tol = NEAR_ZERO) static
Determines the intersection between a line segment and triangle in 3D.
Adapted from O'Rourke, p. 238.
Parameters
seg a line segment in 3D
t a triangle in 3D
isect contains the point of intersection, if any (on return)
isect2 contains a second point of intersection, if the intersection type is seg_tri_inside, seg_tri_edge_overlap, or seg_tri_planar_intersect (on return)
Returns
eSegTriInside (if the segment lies wholly within the face of the triangle), eSegTriVertex (if an endpoint of the segment coincides with a vertex of the triangle), eSegTriEdge (if an endpoint of the segment is in the relative interior of an edge of the triangle), eSegTriFace (if an endpoint of the segment is in the relative interior of the face of the triangle), eSegTriInclVertex (if the open segment includes a vertex of the triangle), eSegTriInclEdge (if the open segment includes a point in the relative interior of an edge of the triangle), eSegTriInclFace (if the open segment includes a point in the relative interior of a face of the triangle), eSegTriEdgeOverlap (if the segment overlaps one edge of the triangle [or vice versa]), eSegTriPlanarIntersect (if the segment lies partially within the face of the triangle), or eSegTriNoIntersect (if there is no intersection).
CompGeom::SegTriIntersectType CompGeom::intersect_seg_tri (const LineSeg2 & seg, const Point2d tri[3], Point2d & isect, Point2d & isect2, double tol = NEAR_ZERO) static
Determines the intersection between a line segment and triangle in 2D.
Parameters
seg a line segment in 2D
tri a triangle in 2D
isect contains the point of intersection, if any (on return)
isect2 contains a second point of intersection, if the intersection type is eSegTriInside, eSegTriEdgeOverlap, or eSegTriPlanarIntersect (on return)
Returns
eSegTriInside (if the segment lies wholly within the triangle face eSegTriVertex (if an endpoint of the segment coincides with a vertex of the triangle), eSegTriEdge (if an endpoint of the segment is in the relative interior of an edge of the triangle), eSegTriEdgeOverlap (if the segment overlaps one edge of the triangle [or vice versa]), eSegTriPlanarIntersect (if the segment lies partially within the face of the triangle), or eSegTriNoIntersect (if there is no intersection).
Note
assumes triangle is oriented ccw
CompGeom::SegSegIntersectType CompGeom::intersect_segs (const LineSeg3 & s1, const LineSeg3 & s2, Point3d & isect, Point3d & isect2) static
Determines whether two line segments in 3D intersect.
Parameters
s1 the points of the first line segment
s2 the points of the second line segment
isect the point of intersection (if any)
isect2 the second point of intersection (for edge intersection)
Returns
the intersection type (edge, vertex, true_intersect, no_intersect); an edge intersection indicates that the segments collinearly overlap; vertex intersection indicates that an endpoint of one segment is on the other segment, but edge intersection does not hold; true_intersect indicates that the segments intersect at a single point.
CompGeom::SegSegIntersectType CompGeom::intersect_segs (const LineSeg2 & s1, const LineSeg2 & s2, Point2d & isect, Point2d & isect2) static
Determines whether two line segments in 2D intersect.
Taken from O'Rourke, p. 224.
Parameters
s1 the points of the first line segment
s2 the points of the second line segment
isect the point of intersection (if any)
isect2 the second point of intersection (for edge intersection)
Returns
the intersection type (edge, vertex, true_intersect, no_intersect); an edge intersection indicates that the segments collinearly overlap; vertex intersection indicates that an endpoint of one segment is on the other segment, but edge intersection does not hold; true_intersect indicates that the segments intersect at a single point.
template<class OutputIterator > OutputIterator Moby::CompGeom::intersect_segs (const LineSeg2 & s1, const LineSeg2 & s2, OutputIterator output_begin) static
Intersects two line segments in 2D.
Parameters
seg1 the first line segment
seg2 the second line segment
output_begin an iterator to the beginning of a container of Point2d; points of intersection will be stored here on return
Returns
an iterator to the end of a container of Point2d; points of intersection will be stored here on return
template<class OutputIterator > OutputIterator Moby::CompGeom::intersect_segs (const LineSeg2 & s1, const LineSeg2 & s2, OutputIterator output_begin)
Intersects two line segments in 2D.
Parameters
seg1 the first line segment
seg2 the second line segment
output_begin an iterator to the beginning of a container of Point2d; points of intersection will be stored here on return
Returns
an iterator to the end of a container of Point2d; points of intersection will be stored here on return
template<class OutputIterator > OutputIterator Moby::CompGeom::intersect_tris (const Point2d t1[3], const Point2d t2[3], OutputIterator output_begin) static
Intersects two 2D triangles.
Note
this method adapted from www.geometrictools.com
template<class OutputIterator > OutputIterator Moby::CompGeom::intersect_tris (const Triangle & t1, const Triangle & t2, OutputIterator begin) static
Intersects two triangles in 3D and returns the points of intersection.
Parameters
begin an iterator to a container that can hold the points of intersection (i.e., a container of size 6 or greater of Ravelin::Vector3 objects); on return, the container will contain a ccw polygon (in 3D) [orientation with respect to the given normal]
Returns
the end of the container output
template<class OutputIterator > OutputIterator Moby::CompGeom::intersect_tris (const Triangle & t1, const Triangle & t2, OutputIterator begin)
Intersects two triangles in 3D and returns the points of intersection.
Parameters
begin an iterator to a container that can hold the points of intersection (i.e., a container of size 6 or greater of Ravelin::Vector3 objects); on return, the container will contain a ccw polygon (in 3D) [orientation with respect to the given normal]
Returns
the end of the container output
References Moby::Triangle::calc_normal().
template<class OutputIterator > OutputIterator Moby::CompGeom::intersect_tris (const Point2d t1[3], const Point2d t2[3], OutputIterator output_begin)
Intersects two 2D triangles.
Note
this method adapted from www.geometrictools.com
template<class ForwardIterator > CompGeom::PolygonLocationType Moby::CompGeom::polygon_location (ForwardIterator begin, ForwardIterator end, const Point2d & point) static
Determines whether a 2D point is inside a polygon.
Adapted from O'Rourke, p. 244.
Parameters
polygon a vector of points that describe a polygon (orientation irrelevant); each successive vertex in the vector is connected to the previous vector to make the polygon (polygon.front() and polygon.back() are connected as well)
point the point to test
Returns
inside_poly if point is inside the polygon, on_vertex if the point coincides with a vertex, on_edge if the point lies on an edge of the polygon (but not a vertex), or outside_poly if the point is outside of the polygon
template<class ForwardIterator > CompGeom::PolygonLocationType Moby::CompGeom::polygon_location (ForwardIterator begin, ForwardIterator end, const Point2d & point)
Determines whether a 2D point is inside a polygon.
Adapted from O'Rourke, p. 244.
Parameters
polygon a vector of points that describe a polygon (orientation irrelevant); each successive vertex in the vector is connected to the previous vector to make the polygon (polygon.front() and polygon.back() are connected as well)
point the point to test
Returns
inside_poly if point is inside the polygon, on_vertex if the point coincides with a vertex, on_edge if the point lies on an edge of the polygon (but not a vertex), or outside_poly if the point is outside of the polygon
template<class ForwardIterator > void Moby::CompGeom::project_plane (ForwardIterator begin, ForwardIterator end, const Ravelin::Vector3d & normal, double offset) static
Projects a set of points onto a plane.
This method is intended to be used with fit_plane() to project the set of points exactly onto a plane; note that this method is unnecessary if the points fit a plane exactly.
template<class ForwardIterator > void Moby::CompGeom::project_plane (ForwardIterator begin, ForwardIterator end, const Ravelin::Vector3d & normal, double offset)
Projects a set of points onto a plane.
This method is intended to be used with fit_plane() to project the set of points exactly onto a plane; note that this method is unnecessary if the points fit a plane exactly.
bool CompGeom::query_intersect_tri_tri (const Triangle & t0, const Triangle & t1) static
Determines whether two triangles intersect.
Returns
true if the triangles intersect
Note
adapted from www.geometrictools.com
References Moby::Triangle::a, Moby::Triangle::b, and Moby::Triangle::c.
static bool Moby::CompGeom::rel_equal (double x, double y, double tol = NEAR_ZERO) inline static
Determines whether two numbers are relatively/absolutely equal to within some tolerance.
If the numbers are both smaller than zero, an absolute tolerance is used; otherwise, a relative tolerance is used.
Note
rationale for why this test is useful: [Ericson, 2005] p. 443
Referenced by Moby::BoxPrimitive::calc_dist_and_normal().
template<class ForwardIterator , class OutputIterator > OutputIterator Moby::CompGeom::to_2D (ForwardIterator begin_source, ForwardIterator end_source, const Ravelin::Matrix3d & R, OutputIterator begin_target) static
Converts a collection of Ravelin::Vector3d objects to Point2d objects
Parameters
source_begin an iterator pointing to the beginning of the Ravelin::Vector3d objects
source_end an iterator pointing to the end of the Ravelin::Vector3d objects
begin_target an iterator pointing to the beginning of the Point2d objects
R the projection matrix from 3D to 2D (on return)
Returns
the end of the output range
Note
the size of the target collection must be equal to the size of the source collection
template<class ForwardIterator , class OutputIterator > OutputIterator Moby::CompGeom::to_2D (ForwardIterator begin_source, ForwardIterator end_source, const Ravelin::Matrix3d & R, OutputIterator begin_target)
Converts a collection of Ravelin::Vector3d objects to Point2d objects
Parameters
source_begin an iterator pointing to the beginning of the Ravelin::Vector3d objects
source_end an iterator pointing to the end of the Ravelin::Vector3d objects
begin_target an iterator pointing to the beginning of the Point2d objects
R the projection matrix from 3D to 2D (on return)
Returns
the end of the output range
Note
the size of the target collection must be equal to the size of the source collection
template<class ForwardIterator , class OutputIterator > OutputIterator Moby::CompGeom::to_3D (ForwardIterator begin_source, ForwardIterator end_source, OutputIterator begin_target, const Ravelin::Matrix3d & RT, double offset) static
Converts a collection of Point2d objects to Ravelin::Vector3d objects
Parameters
source_begin an iterator pointing to the beginning of the Ravelin::Vector3d objects
source_end an iterator pointing to the end of the Ravelin::Vector3d objects
begin_target an iterator pointing to the beginning of the Point2d objects
R the projection matrix from 2D to 3D
offset the offset that must be added to the Z-coordinate of points projected back from 2D to 3D
Returns
the end of the output range
Note
the size of the target collection must be equal to the size of the source collection
template<class ForwardIterator , class OutputIterator > OutputIterator Moby::CompGeom::to_3D (ForwardIterator begin_source, ForwardIterator end_source, OutputIterator begin_target, const Ravelin::Matrix3d & RT, double offset)
Converts a collection of Point2d objects to Ravelin::Vector3d objects
Parameters
source_begin an iterator pointing to the beginning of the Ravelin::Vector3d objects
source_end an iterator pointing to the end of the Ravelin::Vector3d objects
begin_target an iterator pointing to the beginning of the Point2d objects
R the projection matrix from 2D to 3D
offset the offset that must be added to the Z-coordinate of points projected back from 2D to 3D
Returns
the end of the output range
Note
the size of the target collection must be equal to the size of the source collection
template<class ForwardIterator , class OutputIterator > OutputIterator Moby::CompGeom::triangulate_convex_polygon (ForwardIterator source_begin, ForwardIterator source_end, OutputIterator target_begin) static
Triangulates a convex polygon in O(n)
Parameters
source_begin the starting iterator to a connected, ccw-oriented, convex polygon; additionally, the first point is assumed to be connected to the last
source_end the ending iterator to the polygon container
target_begin the starting iterator to the container of triangles
Returns
the ending iterator to the container of triangles
template<class ForwardIterator , class OutputIterator > OutputIterator Moby::CompGeom::triangulate_convex_polygon (ForwardIterator source_begin, ForwardIterator source_end, OutputIterator target_begin)
Triangulates a convex polygon in O(n)
Parameters
source_begin the starting iterator to a connected, ccw-oriented, convex polygon; additionally, the first point is assumed to be connected to the last
source_end the ending iterator to the polygon container
target_begin the starting iterator to the container of triangles
Returns
the ending iterator to the container of triangles
template<class BidirectionalIterator , class OutputIterator > OutputIterator Moby::CompGeom::triangulate_polygon_2D (BidirectionalIterator begin, BidirectionalIterator end, OutputIterator outbegin, double tol)
Triangulates a polygon (in 2D)
Parameters
begin a bidirectional iterator to a container of Point2d objects
end a bidirectional iterator to a container of Point2d objects
outbegin an iterator to a container of type std::pair<const Point2d*, const Point2d*>; output will be written here
tol tolerance to test for zero
Returns
an iterator to the end of the output
Todo:
re-implement using faster O(n lg n) algorithm (currently runs in O(n^2) time)
template<class BidirectionalIterator , class OutputIterator > OutputIterator Moby::CompGeom::triangulate_polygon_2D (BidirectionalIterator begin, BidirectionalIterator end, OutputIterator outbegin, double tol = NEAR_ZERO) static
Triangulates a polygon (in 2D)
Parameters
begin a bidirectional iterator to a container of Point2d objects
end a bidirectional iterator to a container of Point2d objects
outbegin an iterator to a container of type std::pair<const Point2d*, const Point2d*>; output will be written here
tol tolerance to test for zero
Returns
an iterator to the end of the output
Todo:
re-implement using faster O(n lg n) algorithm (currently runs in O(n^2) time)
CompGeom::VisibilityType CompGeom::volume_sign (const Point3d & a, const Point3d & b, const Point3d & c, const Point3d & d, double tol = NEAR_ZERO) static
Gets the sign of the volume of a tetrahedron composed of vertices a, b, c, d.
Returns
-1 if d is "visible" from the plane of (a,b,c); 0 if the a,b,c, and d are coplanar, and +1 otherwise
The documentation for this class was generated from the following files:
/home/drum/Moby/include/Moby/CompGeom.h
/home/drum/Moby/include/Moby/CompGeom.inl
/home/drum/Moby/src/CompGeom.cpp