Moby: Moby::IndexedTetraArray Class Reference
Moby::IndexedTetraArray Class Reference
An array of tetrahedra indexed into shared vertices.
#include <IndexedTetraArray.h>
Public Member Functions
IndexedTetraArray (boost::shared_ptr< const std::vector< Ravelin::Origin3d > > vertices, const std::vector< IndexedTetra > &facets)
IndexedTetraArray (boost::shared_ptr< const std::vector< Ravelin::Origin3d > > vertices, boost::shared_ptr< const std::vector< IndexedTetra > > facets)
template<class ForwardIterator1 , class ForwardIterator2 >
IndexedTetraArray (ForwardIterator1 vertices, ForwardIterator1 verts_end, ForwardIterator2 facets_begin, ForwardIterator2 facets_end)
void center ()
Centers a tetrahedral mesh (returning a new mesh)
unsigned num_tetra () const
IndexedTetraArray transform (const Ravelin::Transform3d &T) const
Transforms this mesh to a new mesh.
IndexedTetraArray compress_vertices () const
Compresses the vertices used in an IndexedTetraArray to create a new mesh.
void write_to_tetra (const std::string &filename) const
void write_to_obj (const std::string &filename) const
IndexedTetraArray & operator= (const IndexedTetraArray &mesh)
Copies one mesh to another.
Tetrahedron get_tetrahedron (unsigned i, boost::shared_ptr< const Ravelin::Pose3d > P) const
Gets the desired tetrahedron.
virtual void load_from_xml (boost::shared_ptr< const XMLTree > node, std::map< std::string, BasePtr > &id_map)
Implements Base::load_from_xml()
virtual void save_to_xml (XMLTreePtr node, std::list< boost::shared_ptr< const Base > > &shared_objects) const
Implements Base::save_to_xml()
boost::shared_ptr< const
std::vector< IndexedTetra > > get_tetra_pointer () const
Gets the pointer to the vector of tetrahedra.
boost::shared_ptr< const
std::vector< Ravelin::Origin3d > > get_vertices_pointer () const
Gets the pointer to the vector of vertices.
const std::vector< IndexedTetra > & get_tetra () const
Gets the vector of facets.
const std::vector
< Ravelin::Origin3d > & get_vertices () const
Gets the vector of verties.
template<class ForwardIterator1 , class ForwardIterator2 >
IndexedTetraArray (ForwardIterator1 verts_begin, ForwardIterator1 verts_end, ForwardIterator2 tetra_begin, ForwardIterator2 tetra_end)
Creates an indexed tetrahedral mesh from containers of vertices and tetra.
Public Member Functions inherited from Moby::Base
Base (const Base *b)
Static Public Member Functions
static IndexedTetraArray read_from_tetra (const std::string &filename)
Reads tetrahedron mesh from a (Moby) .tetra file.
static void write_to_tetra (const IndexedTetraArray &mesh, const std::string &filename)
static void write_to_obj (const IndexedTetraArray &mesh, const std::string &filename)
Static Public Member Functions inherited from Moby::Base
template<class T >
static boost::shared_ptr< T > clone (boost::shared_ptr< T > x)
Static method for cloning a shared pointer.
Additional Inherited Members
Public Attributes inherited from Moby::Base
boost::shared_ptr< void > userdata
Any relevant userdata.
std::string id
The unique ID for this object.
Detailed Description
An array of tetrahedra indexed into shared vertices.
Constructor & Destructor Documentation
template<class ForwardIterator1 , class ForwardIterator2 > Moby::IndexedTetraArray::IndexedTetraArray (ForwardIterator1 verts_begin, ForwardIterator1 verts_end, ForwardIterator2 tetra_begin, ForwardIterator2 tetra_end)
Creates an indexed tetrahedral mesh from containers of vertices and tetra.
Parameters
vertices an iterator to the beginning of a container of Ravelin::Origin3d objects
verts_end an iterator to the end of a container of Ravelin::Origin3d objects
tetra_begin an iterator to the beginning of a container of IndexedTetra objects
tetra_end an iterator to the end of a container of IndexedTetra objects
Member Function Documentation
void IndexedTetraArray::load_from_xml (boost::shared_ptr< const XMLTree > node, std::map< std::string, BasePtr > & id_map) virtual
Implements Base::load_from_xml()
Note
if centering is done, it is done <i<before any transform is applied
Reimplemented from Moby::Base.
References Moby::XMLAttrib::get_bool_value(), Moby::XMLAttrib::get_origin_value(), and Moby::XMLAttrib::get_rpy_value().
The documentation for this class was generated from the following files:
/home/drum/Moby/include/Moby/IndexedTetraArray.h
/home/drum/Moby/include/Moby/IndexedTetraArray.inl
/home/drum/Moby/src/IndexedTetraArray.cpp