Moby: Moby::CSG Class Reference
Moby::CSG Class Reference
Represents a CSG (constructive solid geometry) for collision, visualization, and inertial properties.
#include <CSG.h>
Public Types
enum BooleanOperation { eUnion, eIntersection, eDifference }
Public Member Functions
CSG ()
Constructs a union CSG by default.
CSG (const Ravelin::Pose3d &T)
virtual void load_from_xml (boost::shared_ptr< const XMLTree > node, std::map< std::string, BasePtr > &id_map)
Implements Base::load_from_xml() for serialization.
virtual void save_to_xml (XMLTreePtr node, std::list< boost::shared_ptr< const Base > > &shared_objects) const
Implements Base::save_to_xml() for serialization.
virtual BVPtr get_BVH_root (CollisionGeometryPtr geom)
Gets the bounding volume.
virtual void get_vertices (boost::shared_ptr< const Ravelin::Pose3d > P, std::vector< Point3d > &vertices)
Determines the set of vertices on the surface of the CSG.
virtual double calc_dist_and_normal (const Point3d &p, Ravelin::Vector3d &normal) const
Computes the distance and normal from a point on the CSG.
virtual osg::Node * create_visualization ()
Creates the visualization for this primitive.
virtual boost::shared_ptr
< const IndexedTriArray > get_mesh (boost::shared_ptr< const Ravelin::Pose3d > P)
Returns the mesh (performs a Boolean operation on two CSG operands, if necessary)
void set_operator (BooleanOperation op)
void set_operand1 (PrimitivePtr op1)
void set_operand2 (PrimitivePtr op2)
void set_mesh (boost::shared_ptr< const IndexedTriArray > mesh)
Sets the mesh for this primitive.
PrimitivePtr get_operand1 () const
PrimitivePtr get_operand2 () const
BooleanOperation get_operator () const
virtual void set_pose (const Ravelin::Pose3d &T)
Transforms the CSG.
virtual double calc_signed_dist (boost::shared_ptr< const Primitive > p, boost::shared_ptr< const Ravelin::Pose3d > pose_this, boost::shared_ptr< const Ravelin::Pose3d > pose_p, Point3d &pthis, Point3d &pb) const
Finds the signed distance between the sphere and another primitive.
Public Member Functions inherited from Moby::Primitive
Primitive ()
Constructs a primitive under the identity transformation.
Primitive (const Ravelin::Pose3d &T)
void update_visualization ()
Updates the visualization on the primitive.
void set_mass (double mass)
Sets the mass of this primitive.
void set_density (double density)
Sets the density of this primitive.
virtual Point3d get_supporting_point (const Ravelin::Vector3d &d) const
Gets a supporting point from a primitive.
virtual double calc_signed_dist (const Point3d &p) const
Calculates the signed distance from this primitive.
void add_collision_geometry (CollisionGeometryPtr cg)
Adds a collision geometry.
void remove_collision_geometry (CollisionGeometryPtr cg)
Removes a collision geometry.
boost::shared_ptr< const
Ravelin::Pose3d > get_pose (CollisionGeometryPtr g) const
Gets the pose of this primitive relative to a particular collision geometry.
virtual double get_bounding_radius () const =0
virtual double calc_max_dist (double lin_cont, double ang_cont, double dist, const Ravelin::Vector3d &d0, const Ravelin::Vector3d &w0, boost::shared_ptr< const Ravelin::Pose3d > P)
Computes the maximum distance by a point on the geometry.
virtual bool is_convex () const
Determines whether this primitive is convex.
virtual double calc_dist_and_normal (const Point3d &p, std::vector< Ravelin::Vector3d > &normals) const =0
Computes the distance between a point and this primitive.
virtual double calc_signed_dist (boost::shared_ptr< const Primitive > p, Point3d &pthis, Point3d &pp) const =0
Computes the signed distance between this and another primitive.
virtual osg::Node * get_visualization ()
Gets the visualization for this primitive.
virtual void get_vertices (boost::shared_ptr< const Ravelin::Pose3d > P, std::vector< Point3d > &vertices) const =0
Get vertices corresponding to this primitive.
boost::shared_ptr< const
Ravelin::Pose3d > get_inertial_pose () const
Gets the inertial frame of this primitive.
boost::shared_ptr< const
Ravelin::Pose3d > get_pose () const
Gets the pose of this primitive.
const Ravelin::SpatialRBInertiad & get_inertia () const
Gets the inertia for this primitive.
Public Member Functions inherited from Moby::Base
Base (const Base *b)
Additional Inherited Members
Static Public Member Functions inherited from Moby::Base
template<class T >
static boost::shared_ptr< T > clone (boost::shared_ptr< T > x)
Static method for cloning a shared pointer.
Public Attributes inherited from Moby::Base
boost::shared_ptr< void > userdata
Any relevant userdata.
std::string id
The unique ID for this object.
Protected Attributes inherited from Moby::Primitive
boost::shared_ptr
< Ravelin::Pose3d > _F
The pose of this primitive (relative to the global frame)
boost::shared_ptr
< Ravelin::Pose3d > _jF
The inertial pose of this primitive (relative to the global frame)
boost::shared_ptr< double > _density
The density of this primitive.
Ravelin::SpatialRBInertiad _J
The inertia of the primitive.
std::map< boost::weak_ptr
< CollisionGeometry >
, boost::shared_ptr
< Ravelin::Pose3d > > _cg_poses
The poses of this primitive, relative to a collision geometry.
std::set< boost::shared_ptr
< Ravelin::Pose3d > > _poses
The poses, relative to a particular collision geometry.
Detailed Description
Represents a CSG (constructive solid geometry) for collision, visualization, and inertial properties.
Member Function Documentation
void CSG::set_mesh (boost::shared_ptr< const IndexedTriArray > mesh)
Sets the mesh for this primitive.
Using a precomputed mesh is much faster than my algorithms for computing mesh for a CSG.
References Moby::Primitive::get_pose(), and Moby::Primitive::update_visualization().
Referenced by get_mesh(), and load_from_xml().
The documentation for this class was generated from the following files:
/home/drum/Moby/include/Moby/CSG.h
/home/drum/Moby/src/CSG.cpp